package Popup;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.Map;

public class FileDownloadPopup {
    public static void main(String[] args) throws InterruptedException {
        // Define download path
        String downloadPath = System.getProperty("user.dir") + "\"C:\\Users\\SHAGUN\\Downloads\\info.txt\"";

        // Set Chrome preferences to handle download automatically
        Map<String, Object> prefs = new HashMap<>();
        prefs.put("download.default_directory", downloadPath);
        prefs.put("download.prompt_for_download", false);
        prefs.put("download.directory_upgrade", true);
        prefs.put("safebrowsing.enabled", true);

        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("prefs", prefs);

        // Launch Chrome browser
        WebDriver driver = new ChromeDriver(options);
        driver.manage().window().maximize();

        // Open QSpiders Download page
        driver.get("https://demoapps.qspiders.com/ui/download");

        // Enter some text in the textarea
        WebElement textArea = driver.findElement(By.xpath("//textarea[@placeholder='Filename']"));
        textArea.sendKeys("This is a test file generated by Selenium automation.");

        // Click on Download button
        WebElement downloadBtn = driver.findElement(By.xpath("//button[text()='downloadButton']"));
        downloadBtn.click();

        // Wait for file to download
        Thread.sleep(5000); // better to use FluentWait for real tests

        System.out.println("✅ File downloaded successfully to: " + downloadPath);

        driver.quit();
    }
}


